Repository hashicorp/nomad-autoscaler-demos, pull requests merged in 2021-04, with the labels that each got.

#15 Update AWS permission requirements
  cloud/aws/terraform/modules/aws-hashistack/iam.tf
Labels: theme/aws

#20 vagrant/das: update autoscaler config with DAS block for 0.3.1.
  vagrant/dynamic-app-sizing/jobs/das-autoscaler.nomad
Labels: theme/dynamic-app-sizing, type/enhancement

#19 deps: update Nomad Autoscaler to v0.3.1
  cloud/aws/terraform/modules/aws-hashistack/variables.tf
  cloud/azure/terraform/modules/azure-hashistack/variables.tf
  cloud/gcp/terraform/modules/gcp-hashistack/variables.tf
  vagrant/dynamic-app-sizing/jobs/das-autoscaler.nomad
  vagrant/horizontal-app-scaling/jobs/autoscaler.nomad
Labels: type/enhancement

#21 Update demos to use v0.3.2
  cloud/aws/terraform/modules/aws-hashistack/variables.tf
  cloud/azure/terraform/modules/azure-hashistack/variables.tf
  cloud/gcp/terraform/modules/gcp-hashistack/variables.tf
  vagrant/dynamic-app-sizing/jobs/das-autoscaler.nomad
  vagrant/horizontal-app-scaling/jobs/autoscaler.nomad
Labels: theme/dependency, type/enhancement

#24 admin: remove cgbaker from codeowners file.
  .github/CODEOWNERS
Labels: stage/accepted, theme/admin, type/bug
